---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/sign_in":
    post:
      summary: User login
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: login success
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
