---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
servers:
- url: http://localhost:3000
  description: Local dev server
paths:
  "/users/sign_in":
    post:
      summary: Sign in a user
      tags:
      - Authentication
      parameters:
      - name: Authorization
        in: header
        description: JWT token in Authorization header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: signed in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/api/v1/profile":
    get:
      summary: Show current user profile
      tags:
      - Profile
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Profile data
        '401':
          description: Unauthorized
